services:
  backend:
    build:
      context: ./python-backend
    ports:
      - "8000:8000"
    volumes:
      - ./python-backend:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/your_database
      - OPENAI_API_KEY=SOMECOMBINATIONOFTEXTANDNUMBERS  # OPENAI API KEY GOES HERE! ()
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
